TARGET = nehe06
OBJS = nehe06.o romdisk.o
KOS_ROMDISK_DIR = romdisk

# Update library paths and libraries for SDL3
KOS_LIBS+= -L../../../../build-scripts/build -lSDL3

all: $(TARGET).bin

include $(KOS_BASE)/Makefile.rules

clean:
	rm -f $(OBJS) $(TARGET).elf $(TARGET).bin romdisk.o romdisk.img

$(TARGET).elf: $(OBJS)
	kos-cc -o $(TARGET).elf $(OBJS) -lSDL3 -lGL -lm  -lpthread -lsh4zam

$(TARGET).bin: $(TARGET).elf
	$(KOS_OBJCOPY) -O binary $(TARGET).elf $(TARGET).bin

run: $(TARGET).bin 
	$(KOS_LOADER) $(TARGET).bin
