TARGET = viewbmp
OBJS = viewbmp.o romdisk.o
KOS_ROMDISK_DIR = romdisk
 
# Update library paths and libraries for SDL3
#KOS_LIBS+= -L../../../../build-scripts/build -lSDL3

all: $(TARGET).bin

include $(KOS_BASE)/Makefile.rules

clean:
	rm -f $(OBJS) $(TARGET).elf $(TARGET).bin romdisk.img

$(TARGET).elf: $(OBJS)
	kos-cc -DDREAMCAST -o $(TARGET).elf $(OBJS) -lSDL3 -lGL -lm -lkosutils -lpthread

$(TARGET).bin: $(TARGET).elf
	$(KOS_OBJCOPY) -O binary $(TARGET).elf $(TARGET).bin

run: $(TARGET).bin 
	$(KOS_LOADER) $(TARGET).bin
